#!/bin/bash

HB_DPA=10.64.205.162
echo ; curl -u "$user1":"$pswd1" -H "Accept: application/vnd.emc.apollo-v1+xml" -H "Content-Type: application/vnd.emc.apollo-v1+xml" -X GET "$URL1" > tmp1.txt ; echo; echo; echo "CURRENT DPA SERVER $HB_DPA SETTINGS"; echo "======================================"; echo; cat tmp1.txt; echo; echo
oldtout1=`cat tmp1.txt | grep -i timeout | awk -F"timeout" '{print $2}' | awk -F">" '{print $2}' | awk -F"<" '{print $1}'` ; oldbmul1=`cat tmp1.txt | grep -i binaryMultiplier | awk -F"binaryMultiplier" '{print $2}' | awk -F">" '{print $2}' | awk -F"<" '{print $1}'` ; oldport1=`cat tmp1.txt | grep -i port | awk -F"port" '{print $2}' | awk -F">" '{print $2}' | awk -F"<" '{print $1}'` ; oldmfrm1=`cat tmp1.txt | grep -i mailFrom | awk -F"mailFrom" '{print $2}' | awk -F">" '{print $2}' | awk -F"<" '{print $1}'` ; oldmsvr1=`cat tmp1.txt | grep -i mailServer | awk -F"mailServer" '{print $2}' | awk -F">" '{print $2}' | awk -F"<" '{print $1}'`
cat tmp1.txt | grep -i "<serverSettings" > tmp11.xml ; cat tmp1.txt | grep -i "<id>" >> tmp11.xml ; cat tmp1.txt | grep -i "<link" >> tmp11.xml ; rm -rf tmp1.txt ; echo ; echo "EXISTING VALUE" ; echo "==============" ; echo "timeout = $oldtout1" ; echo "binaryMultiplier = $oldbmul1" ; echo "port = $oldport1" ; echo "mailFrom = $oldmfrm1" ; echo "mailServer = $oldmsvr1" ; echo ; echo "NOW PUT NEW VALUE" ; echo "=================" ; echo -n "timeout = " ; read -e newtout1 ; echo -n "binaryMultiplier = " ; read -e newbmul1 ; echo -n "port = " ; read -e newport1 ; echo -n "mailFrom = " ; read -e newmfrm1 ; echo -n "mailServer = " ; read -e newmsvr1 ; echo ; echo "NEW VALUE THAT YOU JUST PUT" ; echo "===========================" ; echo "timeout = $newtout1" ; echo "binaryMultiplier = $newbmul1" ; echo "port = $newport1" ; echo "mailFrom = $newmfrm1" ; echo "mailServer = $newmsvr1"
echo "   <timeout>$newtout1</timeout> " >> tmp11.xml ; echo "   <binaryMultiplier>$newbmul1</binaryMultiplier> " >> tmp11.xml ; echo "   <port>$newport1</port> " >> tmp11.xml ; echo "   <mailFrom>$newmfrm1</mailFrom>" >> tmp11.xml ; echo "   <mailServer>$newmsvr1</mailServer>" >> tmp11.xml ; echo "</serverSettings>" >> tmp11.xml
echo ; echo "NEW XML" ; echo "=======" ; cat tmp11.xml ; echo ; echo ; curl -v -u "$user1":"$pswd1" -H "Accept: application/vnd.emc.apollo-v1+xml" -H "Content-Type: application/vnd.emc.apollo-v1+xml" -X PUT -T tmp11.xml "$URL1" > tmp2.txt
echo ; cat tmp2.txt ; echo ; echo ; rm -rf tmp11.xml ; rm -rf tmp2.txt
